### ISSUE TITLE
Include hs-sdl2-image in engine's --recursive clone

### ISSUE THREAD

**Issue by jpt4** [wizardsportz/engine#19]
Is there any reason to require wizardsportz/hs-sdl2-image to be cloned separately from the other repositories?

**Comment by jpt4** [comment]
For that matter, give interp source instead of compiled Repl.hs.

**Comment by gavwhela** [comment]
Yes, the reason for that is that git submodules should really only be used when you have a repo dependent on another that will depend on different versions of the subrepo over time. hs-sdl2-image is merely a change in the to hs-sdl2-image cabal file to allow it to be installed with current releases of ghc, so even if there were more changes to hs-sdl2-image we always want to depend on the most recent version. Really, our fork of hs-sdl2-image should be pushed upstream to hackage so that cloning that repo in not needed, but to do that I probably would need to contact the maintainer. As for you second comment, I don't really know what you mean, could you elaborate?

**Comment by jpt4** [comment]
First point acknowledged, thank you.

Regarding point two, I have re-assessed my position and see the wisdom of keeping interpreter and engine development separate.

**Comment by gavwhela** [comment]
Ah, I understand what you were asking. Actually the interp repo is not really part of the wizardsportz implementation anymore. It was merge (not properly, so history wasn't copied) into the engine repo when the engine was first being developed. At this point quite a few changes have been made to the implementation of the interpreter used for the actually wizardsportz implementation. You will find this version in the Wizard/Interp folder. The idea is the version for wizardsportz is quite specialized as a level writing lisp, with some special data structures and built in functions. At some point however, the interp repo will likely be revived into a separate general implementation of lisp with some of the changes in the engine repo merged over to the interp repo.

**Comment by jpt4** [comment]
So, no Wizard repl for the time being?

**Comment by gavwhela** [comment]
Also, both assets and wizard_draw, are deprecated. All level development for the first game release will be moved to a separate repo under it's own license.

**Comment by gavwhela** [comment]
The repl in both the interp repo and the engine repo should work to test out wizardlisp behaivor, however the actually wizardlisp that is interpreted has different capabilities and performance characteristics in each repo.

**Comment by jpt4** [comment]
QSL, vielen Dank.

**Comment by gavwhela** [comment]
Also, you said compiled Repl.hs earlier. There is no compiled versions of the code in the repo currently. Repl.hs is a source file that can be compiled with:
ghc -O3 --make -outputdir build/ Repl.hs

**Comment by jpt4** [comment]
Yes, that was an incorrect assertion.
